"""initial

Revision ID: 4f8ac21cc934
Revises: 
Create Date: 2026-01-27 13:51:21.332306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8ac21cc934'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('COURSE', 'SCHOLARSHIP', 'INTERNSHIP', name='offertype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'EXPIRED', 'DELETED', name='offerstatus'), nullable=False),
           sa.Column('publication_date', sa.DateTime(timezone=True), nullable=False),
           sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=False),
           sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
           sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
           sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('deletion_reason', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_institution_id'), 'offers', ['institution_id'], unique=False)
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_index(op.f('ix_offers_type'), 'offers', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_type'), table_name='offers')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_index(op.f('ix_offers_institution_id'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
